### ISSUE TITLE
Missing #include <QIODevice> in settingsmanager.h!

### ISSUE THREAD

**Issue by mohsenti** [srazi/Saaghar#4]
Hi,
I try to compile a clone of your repo but compile failed with "QIODevice not declare in this scope" error in settingsmanager.h so I add #include <QIODevice> and error gone.

**Comment by srazi** [comment]
Hi,
What are your compiler, OS and Qt version?
Just as a suggestion: did you try clean build?

**Comment by mohsenti** [comment]
>What are your compiler, OS and Qt version?

Compiler : g++ (GCC) 6.1.1 20160501
OS : ArchLinux
Qt : 5

> Just as a suggestion: did you try clean build?

yes.nothing's changed.
