### ISSUE TITLE
error saving settings in root directory

### ISSUE THREAD

**Issue by AmirAref** [srazi/Saaghar#9]
Hi,
I've installed saaghar v3 in my arch linux os from aur.
When i closing the app or changing anything in settings, the app will raise an error that can't save `/settings.ini` and as it shows, it's trying to save settings data in root directory and has no permission to that.
I also compiled the app from the source code and this problem was still happened.

![image](https://github.com/srazi/Saaghar/assets/81515807/41e52808-ca48-43c5-982b-49de70cbeb81)

**Comment by srazi** [comment]
Thanks for your report.
